"use client"

import { useState } from "react"
import { ChevronDown, ChevronRight, ArrowRight, Check } from "lucide-react"
import type { SearchEventData, ProxyTiming } from "@/lib/admin/types"

interface SearchPipelineCardProps {
  event: {
    event_data: SearchEventData
    timestamp: string
  }
  /** Aspects generated by the AI (from correlated aspect_generation event) */
  aspectsGenerated?: string[]
  defaultExpanded?: boolean
}

function PipelineDot({ color }: { color: string }) {
  return (
    <div
      className={`w-3 h-3 rounded-full border-2 shrink-0 ${color}`}
    />
  )
}

function StepCard({
  stepNumber,
  label,
  borderColor,
  dotColor,
  isLast,
  children,
}: {
  stepNumber: number
  label: string
  borderColor: string
  dotColor: string
  isLast: boolean
  children: React.ReactNode
}) {
  return (
    <div className="flex gap-3">
      {/* Timeline connector */}
      <div className="flex flex-col items-center pt-3">
        <PipelineDot color={dotColor} />
        {!isLast && (
          <div className="flex-1 w-px border-l-2 border-dashed border-slate-200 mt-1" />
        )}
      </div>

      {/* Step content */}
      <div className={`flex-1 mb-4 rounded-lg border ${borderColor} bg-white p-3`}>
        <p className="text-[10px] uppercase tracking-wider text-slate-400 font-semibold mb-1.5">
          Step {stepNumber} &mdash; {label}
        </p>
        {children}
      </div>
    </div>
  )
}

function LatencyBar({
  timing,
  queryTime,
}: {
  timing: ProxyTiming
  queryTime: number // backend self-reported, in seconds
}) {
  const backendProcessingMs = Math.round(queryTime * 1000)
  const networkOverheadMs = Math.max(0, timing.backend_ms - backendProcessingMs)
  const redisMs = timing.redis_ms
  const totalMs = timing.total_ms || 1 // avoid division by zero

  const segments = [
    ...(redisMs > 0
      ? [{ label: "Redis config", ms: redisMs, color: "bg-amber-400" }]
      : []),
    ...(networkOverheadMs > 0
      ? [{ label: "Network", ms: networkOverheadMs, color: "bg-blue-400" }]
      : []),
    { label: "Backend", ms: backendProcessingMs, color: "bg-green-400" },
  ]

  return (
    <div>
      <div className="flex h-2.5 rounded-full overflow-hidden bg-slate-200">
        {segments.map((seg, i) => (
          <div
            key={i}
            className={`${seg.color} transition-all`}
            style={{ width: `${Math.max((seg.ms / totalMs) * 100, 2)}%` }}
            title={`${seg.label}: ${Math.round(seg.ms)}ms`}
          />
        ))}
      </div>
      <div className="flex flex-wrap gap-3 mt-1.5">
        {segments.map((seg, i) => (
          <div key={i} className="flex items-center gap-1.5">
            <div className={`w-2 h-2 rounded-sm ${seg.color}`} />
            <span className="text-[11px] text-slate-600">
              {seg.label}: <span className="font-medium">{Math.round(seg.ms)}ms</span>
            </span>
          </div>
        ))}
        <span className="text-[11px] text-slate-500 font-medium ml-auto">
          Total: {Math.round(timing.total_ms)}ms
        </span>
        {timing.aspects_failed && (
          <span className="text-[10px] font-semibold uppercase tracking-wide text-red-600">
            Aspects failed
          </span>
        )}
      </div>
    </div>
  )
}

export default function SearchPipelineCard({
  event,
  aspectsGenerated,
  defaultExpanded = false,
}: SearchPipelineCardProps) {
  const [expanded, setExpanded] = useState(defaultExpanded)
  const d = event.event_data

  const ts = new Date(event.timestamp).toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  })

  const queryChanged = d.enriched_query !== d.user_query

  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
      {/* Collapsed bar */}
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center gap-3 px-4 py-3 text-left hover:bg-slate-50 transition-colors"
      >
        {expanded ? (
          <ChevronDown className="w-4 h-4 text-slate-400 shrink-0" />
        ) : (
          <ChevronRight className="w-4 h-4 text-slate-400 shrink-0" />
        )}
        <span className="text-xs text-slate-400 font-medium whitespace-nowrap">
          {ts}
        </span>
        <span className="text-sm text-slate-800 font-medium truncate flex-1 min-w-0">
          {d.user_query}
        </span>
        <span className="text-xs text-slate-500 whitespace-nowrap">
          {d.results_count} results
        </span>
        {d.proxy_timing ? (
          <span className="text-xs text-slate-400 whitespace-nowrap">
            {Math.round(d.proxy_timing.total_ms)}ms
          </span>
        ) : (
          <span className="text-xs text-slate-400 whitespace-nowrap">
            {d.query_time.toFixed(2)}s
          </span>
        )}
      </button>

      {/* Expanded pipeline view */}
      {expanded && (
        <div className="px-4 pb-4 pt-1 border-t border-slate-100">
          {/* Latency breakdown */}
          {d.proxy_timing && (
            <div className="mb-4 p-3 bg-slate-50 rounded-lg border border-slate-200">
              <p className="text-[10px] uppercase tracking-wider text-slate-400 font-semibold mb-2">
                Latency Breakdown
              </p>
              <LatencyBar timing={d.proxy_timing} queryTime={d.query_time} />
            </div>
          )}

          {/* Step 1 - Original Query */}
          <StepCard
            stepNumber={1}
            label="Original Query"
            borderColor="border-slate-200"
            dotColor="border-slate-400 bg-slate-100"
            isLast={false}
          >
            <p className="text-sm text-slate-800 font-medium">{d.user_query}</p>
          </StepCard>

          {/* Step 2 - Query Augmentation */}
          <StepCard
            stepNumber={2}
            label="Query Augmentation"
            borderColor="border-blue-200"
            dotColor="border-blue-500 bg-blue-100"
            isLast={false}
          >
            {queryChanged ? (
              <div className="flex flex-wrap items-center gap-2">
                <span className="text-sm text-slate-500 line-through">
                  {d.user_query}
                </span>
                <ArrowRight className="w-4 h-4 text-blue-400 shrink-0" />
                <span className="text-sm text-blue-700 font-medium">
                  {d.enriched_query}
                </span>
                {d.product_keyword && (
                  <span className="inline-block px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide rounded-full bg-emerald-100 text-emerald-700">
                    keyword: {d.product_keyword}
                  </span>
                )}
              </div>
            ) : (
              <div className="flex flex-wrap items-center gap-2">
                <p className="text-sm text-slate-500 italic">
                  No augmentation &mdash; query unchanged
                </p>
                {d.product_keyword && (
                  <span className="inline-block px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide rounded-full bg-emerald-100 text-emerald-700">
                    keyword: {d.product_keyword}
                  </span>
                )}
              </div>
            )}
          </StepCard>

          {/* Step 3 - Aspect Selection */}
          <StepCard
            stepNumber={3}
            label="Aspect Selection"
            borderColor="border-purple-200"
            dotColor="border-purple-500 bg-purple-100"
            isLast={false}
          >
            {aspectsGenerated && aspectsGenerated.length > 0 ? (
              <div>
                <div className="flex flex-wrap gap-1.5">
                  {aspectsGenerated.map((aspect, i) => {
                    const isSelected = d.selected_aspects?.includes(aspect)
                    return (
                      <span
                        key={i}
                        className={`inline-flex items-center gap-1 px-2 py-0.5 text-xs font-medium rounded-full border ${
                          isSelected
                            ? "bg-purple-100 text-purple-700 border-purple-300"
                            : "bg-white text-slate-400 border-slate-200"
                        }`}
                      >
                        {isSelected && <Check className="w-3 h-3" />}
                        {aspect}
                      </span>
                    )
                  })}
                </div>
                {d.selected_aspects && d.selected_aspects.length > 0 && (
                  <p className="text-[11px] text-slate-400 mt-1.5">
                    {d.selected_aspects.length} of {aspectsGenerated.length} selected
                  </p>
                )}
              </div>
            ) : d.selected_aspects && d.selected_aspects.length > 0 ? (
              <div className="flex flex-wrap gap-1.5">
                {d.selected_aspects.map((aspect, i) => (
                  <span
                    key={i}
                    className="inline-block px-2 py-0.5 bg-purple-50 text-purple-700 text-xs font-medium rounded-full border border-purple-200"
                  >
                    {aspect}
                  </span>
                ))}
              </div>
            ) : (
              <p className="text-sm text-slate-400 italic">None</p>
            )}
          </StepCard>

          {/* Step 4 - Final Query */}
          <StepCard
            stepNumber={4}
            label="Final Query"
            borderColor="border-teal-200"
            dotColor="border-teal-500 bg-teal-100"
            isLast={false}
          >
            <code className="block text-sm text-teal-800 bg-teal-50 rounded px-2.5 py-1.5 font-mono break-words">
              {d.final_query}
            </code>
          </StepCard>

          {/* Step 5 - Results */}
          <StepCard
            stepNumber={5}
            label="Results"
            borderColor="border-green-200"
            dotColor="border-green-500 bg-green-100"
            isLast={true}
          >
            <div className="flex flex-wrap items-center gap-2 mb-2">
              <span className="text-sm font-semibold text-slate-800">
                {d.results_count} product{d.results_count !== 1 ? "s" : ""}
              </span>
              <span className="text-xs text-slate-400">
                in {d.query_time.toFixed(2)}s
                {d.proxy_timing && (
                  <> ({Math.round(d.proxy_timing.total_ms)}ms total)</>
                )}
              </span>
              <span
                className={`inline-block px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide rounded-full ${
                  d.filter_in_place
                    ? "bg-amber-100 text-amber-700"
                    : "bg-green-100 text-green-700"
                }`}
              >
                {d.filter_in_place ? "Filter-in-place" : "Full pipeline"}
              </span>
              {d.search_mode && (
                <span className="inline-block px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide rounded-full bg-blue-100 text-blue-700">
                  {d.search_mode}
                </span>
              )}
            </div>

            {d.result_ids_titles && d.result_ids_titles.length > 0 ? (
              <ul className="space-y-1">
                {d.result_ids_titles.slice(0, 5).map((item, i) => (
                  <li
                    key={item.id}
                    className="flex items-baseline gap-2 text-xs text-slate-600"
                  >
                    <span className="text-slate-300 font-mono shrink-0">
                      {i + 1}.
                    </span>
                    <span className="truncate">{item.title}</span>
                  </li>
                ))}
                {d.result_ids_titles.length > 5 && (
                  <li className="text-xs text-slate-400 pl-5">
                    +{d.result_ids_titles.length - 5} more
                  </li>
                )}
              </ul>
            ) : (
              <p className="text-xs text-slate-400 italic">No results</p>
            )}
          </StepCard>
        </div>
      )}
    </div>
  )
}
